// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountProducts(ctx context.Context, arg CountProductsParams) (int64, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	DeleteProduct(ctx context.Context, id uuid.UUID) error
	GetCategories(ctx context.Context) ([]string, error)
	GetProductByID(ctx context.Context, id uuid.UUID) (Product, error)
	GetProductStats(ctx context.Context) (GetProductStatsRow, error)
	GetProducts(ctx context.Context, arg GetProductsParams) ([]Product, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
